### ISSUE TITLE
[question] untrusted module init

### ISSUE THREAD

**Issue by hellower** [RhodiumToad/pllua-ng#1]
$> luarocks intall http ---  untrusted lua module because of including IO module.

plinit.module tables don't allow 'http' module in Old pllua.

 I found new pllua extension => pllua_ng

How Can I  load 'http' module?

I have read the document but I do not understand it.
I would appreciate a more specific example.

postgresq.conf parameter?
pllua.on_init
pllua.on_untruested_init 

sorry for my poor english.

**Comment by RhodiumToad** [comment]
In untrusted-language code (plluau) you can just require the module as needed:

```
create function fetchbody(uri text)
  returns text
  language plluau
as $$
    local hdr,str = http_req.new_from_uri(uri):go()
    return str:get_body_as_string()
end
do
    http_req = require 'http.request'
$$;

select fetchbody('http://detectportal.firefox.com/success.txt');
```

(this works in the old plluau too except that you'd use the _U upvalue to store the module rather than assuming a local environment)

The stuff with the init strings is for the benefit of people who want to do one of three things:

1) they want to make untrusted modules available to the **trusted** interpreter - this is dangerous, since unprivileged users can use the trusted interpreter, and if they can use loaded modules to gain access to the filesystem then they can use that to violate security; but it's the only way to, for example, make useful and safe modules like lpeg available to unprivileged users;

2) they want to load a lot of modules and reduce session startup overhead by preloading everything in the postmaster process.

3) they have a lot of modules that they use widely and prefer to load into the global namespace rather than do 'require' in each function.

Examples of each case:

1) (in postgresql.conf)
```
pllua.on_trusted_init = 'trusted.allow("lpeg") trusted.allow("re")'
```
then in sql,
```
do language pllua $$ re = require 're'  --[[ do stuff with re.* funcs ]] $$
```

2) (in postgresql.conf)
```
shared_preload_libraries = 'pllua'
pllua.on_init = 'require "mymodules"'
```
(this does the actual work of creating the Lua state and reading the modules when pg is started or the on_init string is changed, and "require" calls to the loaded modules are satisfied from the table of loaded modules)

3) (in postgresql.conf)
```
pllua.on_untrusted_init = 'foo = require "foo"  bar = require "bar"'
```

**Comment by hellower** [comment]
Thanks!!!

**Comment by daurnimator** [comment]
> local hdr,str = http_req.new_from_uri(uri):go()

PS, make sure you handle errors with this e.g. with `assert`
